---
- name : Create Datacenter
  hosts: localhost

  tasks:
  - name: Get playbook variables
    include_vars:
      file: variable.yml

  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: "{{ 192.168.100.49 }}"
      username: "{{ administrator@dupont.lan }}"
      password: "{{ Esgi1234! }}"
      datacenter_name: "{{ nom }}.{{ prenom }}"
      state: present
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
